name = "WaveletOperators"
uuid = "f3582904-6f60-4bbd-985d-55eab799bc9d"
authors = ["Tamas Hakkel <hakkelt@gmail.com>"]
version = "0.1.0"

[deps]
AbstractOperators = "d9c5613a-d543-52d8-9afd-8f241a8c3f1c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OperatorCore = "3945cd23-d97e-4db0-9df2-35342dbd287d"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
LinearAlgebra = "1.11.0"
OperatorCore = "0.1"
Wavelets = "0.10.1"
